In [1]:
import numpy as np 

In [2]:
# data types and attributes 
# numpy  main data type is nd array 
al = np.array([1,2,4])

In [3]:
type(al)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3,4,5.0],[1,2,3,4,5,1]])

In [5]:
a2

array([list([1, 2, 3, 4, 5.0]), list([1, 2, 3, 4, 5, 1])], dtype=object)

In [6]:
a2.shape

(2,)

In [7]:
a3 = np.array([[1,2,3],
              [1,2,4]])

In [8]:
a3

array([[1, 2, 3],
       [1, 2, 4]])

In [9]:
type(a3)

numpy.ndarray

In [10]:
a3.ndim

2

In [11]:
a3.shape

(2, 3)

In [12]:
a2.shape

(2,)

In [13]:
a3.size

6

In [14]:
import pandas as pd

In [15]:
df = pd.DataFrame(a3)

In [16]:
# creating arrays

In [17]:
sample = np.array([1,2,4])

In [18]:
sample

array([1, 2, 4])

In [19]:
sample.dtype

dtype('int32')

In [20]:
sample.size

3

In [21]:
sample.ndim

1

In [22]:
sample.shape

(3,)

In [23]:
one = np.ones([2,3],dtype=int)

In [24]:
one

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
one.dtype

dtype('int32')

In [26]:
one.ndim

2

In [27]:
zeros = np.zeros([2,4],dtype=int)

In [28]:
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
zeros 

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
random_array =np.arange(0,20,3)

In [31]:
random_array 

array([ 0,  3,  6,  9, 12, 15, 18])

In [32]:
random_array = np.random.randint(0,19,size=(3,6))

In [33]:
random_array.size

18

In [34]:
random_array = np.random.random((5,3))

In [35]:
random_array 

array([[0.94834107, 0.06137574, 0.99382253],
       [0.48892554, 0.79301048, 0.11676786],
       [0.23847534, 0.99436658, 0.83121894],
       [0.31276911, 0.93090697, 0.4437072 ],
       [0.83466893, 0.4570212 , 0.03358165]])

In [36]:
random_array.shape

(5, 3)

In [37]:
random_array = np.random.rand(2,3)

In [38]:
random_array

array([[0.97818863, 0.46502691, 0.28299439],
       [0.96446057, 0.00463193, 0.55935325]])

In [39]:
random_array.shape

(2, 3)

In [40]:
np.random.seed()
random_array = np.random.rand(3,5)

In [41]:
random_array

array([[0.80930621, 0.13902865, 0.14719869, 0.57330896, 0.59206142],
       [0.40263224, 0.1038913 , 0.33024995, 0.1058351 , 0.30638666],
       [0.73026983, 0.86565202, 0.90372524, 0.30293747, 0.54709165]])

In [42]:
np.random.seed(seed=22)
random_array = np.random.randint(18,size=(3,4))

In [43]:
random_array

array([[ 4, 12,  0,  4],
       [ 6, 11,  8,  4],
       [14, 13,  7,  2]])

In [44]:
# viewing arrays and matrix
np.unique(random_array)

array([ 0,  2,  4,  6,  7,  8, 11, 12, 13, 14])

In [45]:
a3.shape

(2, 3)

In [46]:
random_array1 = np.random.randint(19,size=(3,1,4,5))

In [47]:
random_array1

array([[[[ 9,  8,  8,  5, 15],
         [ 2, 18, 17,  6,  2],
         [ 7,  7, 14, 10,  9],
         [11, 13, 11,  7, 15]]],


       [[[17,  1, 15, 16,  1],
         [12,  9, 17,  3,  4],
         [11,  0, 18, 11,  3],
         [ 6, 15,  0,  7, 16]]],


       [[[14, 17,  8, 10, 10],
         [ 1,  5,  6, 13,  5],
         [ 6, 18,  5,  0,  5],
         [17, 17, 18,  9,  0]]]])

In [48]:
random_array1.size

60

In [49]:
random_array1 = np.random.randint(13,size=(2,3,3,4))

In [50]:
random_array1

array([[[[ 3,  5,  7,  6],
         [ 1, 12,  8,  4],
         [ 8,  9,  8,  5]],

        [[ 5,  5,  4,  4],
         [ 3,  0,  8, 10],
         [ 4,  0,  1,  5]],

        [[ 6,  8,  2,  6],
         [ 5,  6, 10,  6],
         [10,  7,  7, 12]]],


       [[[ 4,  4, 11, 11],
         [ 8,  1,  2,  3],
         [ 6,  0,  3,  9]],

        [[ 3, 10,  6,  9],
         [ 6,  4, 12,  8],
         [ 7,  1,  3, 11]],

        [[ 7,  1,  1,  6],
         [ 2, 12,  8, 12],
         [10,  5, 10,  0]]]])

In [55]:
random_array1[:,:,:,:1] # slicing 

array([[[[ 3],
         [ 1],
         [ 8]],

        [[ 5],
         [ 3],
         [ 4]],

        [[ 6],
         [ 5],
         [10]]],


       [[[ 4],
         [ 8],
         [ 6]],

        [[ 3],
         [ 6],
         [ 7]],

        [[ 7],
         [ 2],
         [10]]]])

In [ ]:
# Manipulating & Comparing arrays 

In [61]:
zero = np.zeros((3,2))

In [62]:
zero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [64]:
a2 = np.random.randint(12,size=(3,2))

In [65]:
a2+zero

array([[ 8.,  1.],
       [11.,  6.],
       [11.,  9.]])

In [66]:
a2 

array([[ 8,  1],
       [11,  6],
       [11,  9]])

In [72]:
a1 = np.array([[[1,2],
             [1,2],
             [1,1]]])

In [81]:
a1//a2

array([[[0, 2],
        [0, 0],
        [0, 0]]], dtype=int32)

In [83]:
a1%a2

array([[[1, 0],
        [1, 2],
        [1, 1]]], dtype=int32)

In [84]:
np.exp(a1)

array([[[2.71828183, 7.3890561 ],
        [2.71828183, 7.3890561 ],
        [2.71828183, 2.71828183]]])

In [85]:
# aggregation

In [ ]:
#Aggregation = Performing the same operation on a number of things

In [86]:
listy_list = [1,2,3,3]

In [87]:
sum(listy_list)

9

In [89]:
type(a1)

numpy.ndarray

In [92]:
np.std(a2)

3.4480268109295333

In [93]:
np.var(a2)

11.888888888888888

In [96]:
massive_array = np.random.random(1000)

In [98]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

322 µs ± 6.29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
9.63 µs ± 733 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [100]:
np.var(a2)

11.888888888888888

In [101]:
np.sqrt(np.var(a2)) # Standard deviation = Square root of varuabce

3.4480268109295333

In [102]:
np.std(a2)

3.4480268109295333

In [103]:
## Reshaping and transposing

In [104]:
a2

array([[ 8,  1],
       [11,  6],
       [11,  9]])

In [106]:
a2.shape

(3, 2)

In [112]:
a1 = np.array([1,2,3])

In [117]:
a1*a2

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [116]:
a1.reshape(3,1)

array([[1],
       [2],
       [3]])

In [118]:
a1.T

array([1, 2, 3])

In [119]:
#dot product
np.dot(a1,a2)

array([63, 40])

In [124]:
a1.T

array([1, 2, 3])

In [121]:
a2

array([[ 8,  1],
       [11,  6],
       [11,  9]])

In [125]:
np.random.seed(0)
# Number of 
sales_amounts = np.random.randint(20,size=(5,3))

In [126]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [130]:
# create a weeky sales data frame 
weekly_sales = pd.DataFrame(sales_amounts,index=["Mon","Tuesday","Wednesday","Thursday","Friday"],
                            columns=['Peanut_Butter','Amool_Butter','Doritos'])

In [131]:
weekly_sales

Peanut_Butter  Amool_Butter  Doritos
Mon                   12            15        0
Tuesday                3             3        7
Wednesday              9            19       18
Thursday               4             6       12
Friday                 1             6        7

In [133]:
prices = np.array([13,18,15])

In [146]:
prices=prices.reshape(1,3)

In [149]:
snacks_prices = pd.DataFrame(prices ,index =['Price'],columns =
                            ['Peanut_Butter','Amool_Butter','Doritos'])

In [150]:
snacks_prices

Peanut_Butter  Amool_Butter  Doritos
Price             13            18       15

In [153]:
total_sales = prices.dot(sales_amounts.T)

In [154]:
total_sales 

array([[426, 198, 729, 340, 226]])

In [156]:
daily_sales = snacks_prices.dot(weekly_sales.T)
daily_sales

Mon  Tuesday  Wednesday  Thursday  Friday
Price  426      198        729       340     226

In [158]:
weekly_sales['Total_sales'] = daily_sales.T

In [161]:
weekly_sales['price'] = snacks_prices.T

In [165]:
weekly_sales['price'].fillna(13)

Mon          13.0
Tuesday      13.0
Wednesday    13.0
Thursday     13.0
Friday       13.0
Name: price, dtype: float64

In [166]:
# Comparison operatotrs

In [ ]:
 # sorting array
    #np.sort()
    #np.argsort() # sorting index 
    

In [170]:
random_array = np.random.randint(10,size=(1,5))

In [172]:
np.sort(random_array)

array([[0, 3, 3, 4, 9]])

In [171]:
random_array

array([[9, 4, 3, 0, 3]])

In [174]:
np.argsort(random_array)  # its giving an index as you see

array([[3, 2, 4, 1, 0]], dtype=int64)

In [175]:
np.argmax(random_array)

0

In [176]:
np.argmin(random_array)

3

In [ ]:
# Findings?
# turning an image to numpy array because we all know pixel are working on numbers and machine identifies everything in numbers 
